### ISSUE TITLE
Is array supported in .env?

### ISSUE THREAD

**Issue by phoenixg** [vlucas/phpdotenv#175]
```PHONES=[number1,number2]```

I want the `[number1,number2]` to be PHP array, how to achieve?

**Comment by GrahamCampbell** [comment]
Sorry, these are not supported.

**Comment by IAmJulianAcosta** [comment]
@GrahamCampbell Can I generate a PR to this functionality?

**Comment by phoenixg** [comment]
@IAmJulianAcosta I hope so

**Comment by GrahamCampbell** [comment]
No thanks. I don't think this is needed.

**Comment by IAmJulianAcosta** [comment]
@phoenixg you can use `FOO="bar, baz, foobar"` and `explode()`

**Comment by bbatsche** [comment]
Not to harp too much on an old issue, but I disagree with the assertion that this would have no value. Putting the burden of parsing string values into arrays on calling code leads to less clean and more error prone code. For example, if I wanted to use a `.env` array value in a static config context, the naive approach would be the following:

```php
// my_config.php
return [
    'some_value' => explode(',', env('SOME_VALUE')),
];
```

Putting aside the issue of extraneous or incorrect data causing incorrect values (such as `', '` in our `.env`) this actually creates greater potential for erroneous data altogether if `SOME_VALUE` has not been defined in our `.env`. Rather than `some_value` being assigned `null` or `[]` as one might expect, it will be assigned an array with a single empty string within it.

Meanwhile, if `phpdotenv` parsed array values on our behalf, the config could simply (and **reliably**) be written as:

```php
// my_config.php
return [
    'some_value' => env('SOME_VALUE', []),
];
```

`some_value`'s intended datatype and fallback value becomes clearer and our client code becomes much more elegant.

Look, obviously the the solution here is to ensure `SOME_VALUE` is defined in `.env` and has at least one usable value, but my point is that it puts more burden on the developer than feels necessary.

**Comment by tuupola** [comment]
Phpdotenv is about storing values in environment, not general purpose config library. Environment is UNIX concept and the values are always interpreted as character strings. Converting to different datatypes such as arrays or booleans would be outside the scope of this class.

It would however be quite easy to create general purpose config library which under the hood uses phpdotenv but automatically converts values to arrays and booleans.

**Comment by GrahamCampbell** [comment]
Yes, exactly @tuupola! Nice to separate concerns.

**Comment by bbatsche** [comment]
Cool! So @GrahamCampbell, when I can I expect those concerns separated out in Laravel's `env()` config loader? :stuck_out_tongue:

Seriously, thank you for entertaining my criticism, I do appreciate the hard work all y'all have done.

**Comment by GrahamCampbell** [comment]
Laravel's config system is already separated. phpdotenv does environment, laravel does config. Then once config is done, environment is ignored. The concern of parsing environment variables from strings into whatever is passed on to laravel (weather that be their env function, or exploding inside your config files).

**Comment by saidbakr** [comment]
@bbatsche The explode solution is not useful, or at least very complicated with multi dimensional arrays. For eaxmple, I have the following settings value in `config/app.php` of my Laravel project:

```
'shiftsColor' => [
        0 => ['fg' => '#FFFFFF', 'bg' => '#211E1E'],
        8 => ['fg' => '#000000', 'bg' => '#FFFFFF'],
        16 =>['fg' => '#032A51', 'bg' => '#FFCE44']
    ],
```

**Comment by FelipeBarrosCruz** [comment]
```php
    $dotEnv = new Dotenv\Dotenv(__DIR__);
    $envArr = array_map(function ($var) {
        $values = explode('=', $var);
        return [$values[0] => $values[1]];
    }, $dotEnv->load());
```

**Comment by vlucas** [comment]
The purpose of this project is to load environment variables from an `.env` file. It mimics how shell already works. It is not a general purpose config library, as already stated here. Unix shell does not support types like array, boolean, etc. so this library will not either.

**Comment by ikari7789** [comment]
I fail to see how arrays are NOT within the scope of this project? Shell variables support arrays, so why should dotenv not also support simple arrays?

**Comment by tuupola** [comment]
Bash might support array variables in shell scripts but arrays cannot be exported to environment.

**Comment by vlucas** [comment]
Yes - sorry I should have clarified further. It's about what can be set with `export` and then read from another context/program, which is the core of what `.env` does. That limits us to basically just strings.
