### ISSUE TITLE
Is this problem when using putenv/getenv function?

### ISSUE THREAD

**Issue by QuangPB** [vlucas/phpdotenv#238]
(sorry for my bad english)

I made a simple test. I have 2 sites in a same Apache server (using virtual host)
With XAMPP stack, apache 2.4, I setup virtual host for 2 folders: test1.com and test2.com
- In test1.com: I put a php file (test1.com/putenvTest.php) with putenv('xxx=1'). After that using curl function to make a http GET request to test2.com/getenvTest.php
- In test2.com: I put getenvTest.php with  var_dump( getenv('xxx') );
- Go to browser and hit test1.com/putenvTest.php => the value 1 is displayed
So, when I call putenv('xxx=1') in one site. I can get that value in other site (over curl request). 
I think this is a problem in some frameworks using dotenv to store .env config such as Laravel.
When I setup 2 Laravel projects (each project have separate folder, and separate .env file), one of them is WEB and other is API, WEB will call API to get data (using curl). Many keys in 2 .env files are the same. So, API will ignore keys was existed because WEB was load that keys => API will get wrong config (these configs are of WEB, not API)

Thanks

**Comment by sisve** [comment]
This happens because Apache on Windows executes all php-requests within the same process, and the first request sets the variables and the second reads them. Dotenv will not overwrite existing variables, that is why the second request don't get all of the second sites .env stuff.

This is a well-known issue and you will have other issues with your setup too, like building localized sites that calls setlocale() which also is process-wide.

Regarding Laravel, you are supposed to run `php artisan config:cache` to build a cached configuration file. This means that values are read from .env and stored in a cached file, and Laravel will no longer call dotenv on every request.

Related: #76 (Changing process environment unsafe on multithreaded servers)

**Comment by GrahamCampbell** [comment]
Thanks, yeh. This is a known issue, with known solutions, the solutions being, don't read the env variables directly, load them once into config.

**Comment by GrahamCampbell** [comment]
The current version of phpdotenv is robust and thread-safe. The following example will work in a multithreaded environment. This avoids using the adapter that would have called `putenv` and `getenv`, which are not threadsafe.

```php
<?php

use Dotenv\Environment\Adapter\EnvConstAdapter;
use Dotenv\Environment\Adapter\ServerConstAdapter;
use Dotenv\Environment\DotenvFactory;
use Dotenv\Dotenv;

$factory = new DotenvFactory([new EnvConstAdapter(), new ServerConstAdapter()]);

Dotenv::create($path, null, $factory)->load();
```
