### ISSUE TITLE
Variables with \n converted to empty strings (after last updating)

### ISSUE THREAD

**Issue by Nur777** [vlucas/phpdotenv#279]
Hi to all!

Before the last updating the next variable was working correctly:
`VARIABLE="Text with\nsome end of lines\n"`
and in the php when i wrote the next code:
`echo env('VARIABLE');`
returns:
`Text with\nsome end of lines\n`

After the last update the variable returns:
`` <- empty string

**Comment by GrahamCampbell** [comment]
Could you pin down which change broke tHis for you please?

**Comment by Korbeil** [comment]
Just tested and I'm having:
`"Text with\nsome end of lines\n"` as return (added `"` at start and end of the string for some strange reason)

env file:
```env
VARIABLE="Text with\nsome end of lines\n"
```

related test:
```php
$this->assertSame('Text with\nsome end of lines\n', getenv('VARIABLE'));
$dotenv->required('VARIABLE');
$dotenv->required('VARIABLE')->notEmpty();
```

**Comment by Korbeil** [comment]
After more testing, when using:
```
VARIABLE="Text with some end of lines"
```

I have: `Text with some end of lines` returned.
I think the quote issue is related to https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L239 which wasn't changed on last release.

I was able to make it work by escaping backslashes:
```
VARIABLE="Text with\\nsome end of lines\\n"
```
This is some old behavior already tested & described in https://github.com/vlucas/phpdotenv/blob/master/tests/fixtures/env/specialchars.env

**Comment by Nur777** [comment]
@Korbeil please try these variable:
`VARIABLE="In the town where I was born\n"`
When creating an issue a used another value for the VARIABLE. But if you try the last variable value you can see that the issue exists.

**Comment by Korbeil** [comment]
@Nur777 Ok, just tried, this is working as you said if the `\` is at the end of the env value. I think this is an edgy case and should not work, since we ask to escape baskslashes and quotes in values. This should throw an exception.

This was introduced by https://github.com/vlucas/phpdotenv/commit/f84952fe8ff11cc6b249b29a8460d03f050a59f3

**Comment by Nur777** [comment]
@Korbeil excuse me, but the `\` is not at the end of env value. Is not it?

**Comment by Nur777** [comment]
@Korbeil but why the string returns correct if i deleting the second big char `I`?

**Comment by Korbeil** [comment]
@Nur777 my bad: if the `\` is after all text.

Since the regex there: https://github.com/vlucas/phpdotenv/blob/f84952fe8ff11cc6b249b29a8460d03f050a59f3/src/Loader.php#L232
Is matching chars then backslashes, it will fails after.

I don't have same issue about the `I` you're talking about, could you share me the version of PHP you're using and the version of the library ?

**Comment by Nur777** [comment]
@Korbeil 
PHP Version => 7.2.6
Vlucas/PhpDotEnv => 2.5.0

Are you tested variable with this string? 
`VARIABLE="In the town where I was born\n"`
it returns correctly? In my PC it returns empty.

**Comment by Nur777** [comment]
I found that:
https://github.com/vlucas/phpdotenv/blob/f84952fe8ff11cc6b249b29a8460d03f050a59f3/src/Loader.php#L227-L242
- after this lines the string `"In the town where I was born\n"` becomes empty.

**Comment by Nur777** [comment]
I make some research and found that the code works somehow strange...
I found this line:
https://github.com/vlucas/phpdotenv/blob/f84952fe8ff11cc6b249b29a8460d03f050a59f3/src/Loader.php#L242
And wrote this code to debug different values:
`
var_dump($name, $value);
$value = preg_replace($regexPattern, '$1', $value); 
var_dump($name, $value); die(1); // For showing the value
`

So, I tested the next values:
1. 
- `VARIABLE="Text of lines\n"' 
- var_dump shows me `""Text of lines\n""` (with double quoutes)
2. 
- `VARIABLE="Text of some lines\n" // var dump shows me NULL`
- var_dump shows me NULL <- why?

**Comment by Nur777** [comment]
@danielstokes the problem isn't only in "\n" as I described above.

**Comment by danielstokes** [comment]
The lines 
https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L250 and 
https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L251 
indicate the escape sequences as well as 
https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L240 and 
https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L241 .
The issue being that in 2.4 it worked because 
```VAR=some\nthing``` would be processed correctly, where as ```VAR="some\nthing"``` would not.  The result would be that VAR still equals '"some\nthing"' (no quotes removed), because it failed to match.  In the case with the change, because a line is slightly longer, it's triggering an error (PREG_BACKTRACK_LIMIT_ERROR), which can be adjusted with pcre.backtrack_limit to bypass the issue.  However, this also means that the value token is not being processed correctly.

tested this with php 5.6, 7.0, 7.2 on windows 10 and ubuntu 16.04.  

@Korbeil I believe the library should have some parse exceptions added.

**Comment by Korbeil** [comment]
> @Korbeil I believe the library should have some parse exceptions added.

I totaly agree on that, but this should be done on next major, not on minor, otherwise you'll have too much people coming to make issues 😄

**Comment by Nur777** [comment]
@danielstokes how I should change my variable value to make him work?
I tested:
1. `Text of SOME lines\n` - it returns `NULL`
2. `"Text of SOME lines\n"` - it returns `NULL`
3. `"Text of lines\n"` - it returns `""Text of lines\n""` (with double-double quotes)

What am doing wrong?

**Comment by Nur777** [comment]
@danielstokes I see that you change the word "Text" to the word "Test"? It is all changes that should I do?

Thx for the solution about the base64!

**Comment by danielstokes** [comment]
My bad.  Mis-typed that, corrected my comment above.  Should have been VAR="Text of SOME lines\\\n".  Also, I just noticed github uses \\\\ as escape code, whould be why you thought that was the only change.

**Comment by franksl** [comment]
As this is sort of a breaking change I think it should be versioned appropriately and well documented, my application simply stopped working after a composer update and it took me quite some time to track down the problem.
Thanks,
Frank

**Comment by jamieburchell** [comment]
A Wordpress installation which is backed by Roots Bedrock, which uses phpdotenv failed with "Unable to establish database connection" when I composer updated this library from 2.4.0 to 2.5.0.

It was a guess that this library was the culprit after seeing it update and it had be completely confused at first. Turns out I have a database password starting with a # in an unquoted string which no longer seems to work with 2.5.0.

**Comment by Korbeil** [comment]
@jamieburchell : you should check #276

**Comment by Nur777** [comment]
@danielstokes Thanks!

**Comment by fyzzy1943** [comment]
#290 the reason is this

**Comment by GrahamCampbell** [comment]
https://github.com/vlucas/phpdotenv/pull/271 will bring first-class support for multiline variables in v3.0.
