### ISSUE TITLE
feature: Use non-String datatypes

### ISSUE THREAD

**Issue by kaHaleMaKai** [vlucas/phpdotenv#286]
Thanks for that fine piece of software you have provided us with! I like it very much.

If I have just missed something in the documentation in the first place, I'm happy and this issue can be closed right away.

Currently, the only thing with `DotEnv` that feels cumbersome, is using non-String datatypes. We can _validate_ them, but we have to _convert_ their value manually, e.g.

```php
$dotenv->required('FOO')->isBoolean();
$_SERVER['FOO'] = $_ENV['FOO'] = filter_var($_ENV['FOO'], FILTER_VALIDATE_BOOLEAN);
```

In most cases I check datatypes for, I will use exactly those datatypes in my code, so I have to cast them. I would appreciate if `DotEnv` would take care of that for me automatically. This approach would lead to a discrepency between `getent()` and the `$_ENV`/`$_SERVER` vars. There might also be a configuration flag for switching that behaviour, so users can opt in manually.

What do you think about it?

**Comment by philippdaun** [comment]
I use a custom version of [Laravel's env() function](https://github.com/laravel/framework/blob/2ab2fc61c3b042d888b43f984535dfed0e754948/src/Illuminate/Support/helpers.php#L590) that does type conversion, unquotes strings and allows for fallback values in case of unset variables. I guess you could make the argument that _phpdotenv_ should include that function or something similar since it'll probably come up anyway.

**Comment by GrahamCampbell** [comment]
Thanks for the suggestion, but I don't want to implement this. I think it's very straightforward if environment variables are always going to be strings, especially if people are using strict typing. It's hard to do good static analysis if the env functions can return other stuff.
