### ISSUE TITLE
[2.6.0] Got DB connection error after update

### ISSUE THREAD

**Issue by makersm** [vlucas/phpdotenv#336]
Hi, I'm using DB connection using .env file.
.env file looks like below :

```
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=homestead_h
DB_USERNAME=homestead
DB_PASSWORD=secret!@#
```

and I got `Access denied for user ~~ ` error. 
After revert phpdotenv's version 2.6.0 to 2.5.2, everything works fine.

**Comment by robtesch** [comment]
Same issue with Laravel project. Tried every possible combination of quotes and no quotes. My password has a # in it if that's any help.

**Comment by zhouzyc** [comment]
@robtesch 
have a try
DB_PASSWORD=secret!@# ->DB_PASSWORD=”secret!@#“

**Comment by erikscheepers** [comment]
Same error here, also a # in the password. Putting the password between quotes fixes the issue.

**Comment by GrahamCampbell** [comment]
Thanks for the report. It looks like we're missing some tests.

**Comment by GrahamCampbell** [comment]
The new version is parsing the hash as a comment.

**Comment by GrahamCampbell** [comment]
I'm prepping a fix now.

**Comment by GrahamCampbell** [comment]
Please let me know if https://github.com/vlucas/phpdotenv/pull/338 fixes your issue. :)

**Comment by GrahamCampbell** [comment]
I've released v2.6.1 with the parser fixes.

**Comment by robtesch** [comment]
@GrahamCampbell thanks very much, that fixed it. Out of interest, for future (v3+) how should we do it? Do we need to escape some chars?

**Comment by GrahamCampbell** [comment]
The two differences are for unquoted strings, as soon as there's a hash, it's treated as a comment start, and we're being stricter about invalid escape sequences.

| input/result | 2.5.2 | 2.6.1 | 3.3.1 |
|-|-|-|-|
| `foo#bar` | `foo#bar` | `foo#bar` | `foo` |
| `foo # bar` | `foo` | `foo` | `foo` |
| `"iiiiviiiixiiiiviiii\n"` | silent failure | `iiiviiiixiiiiviiii\n` | fails with invalid escape sequence exception |
| `"iiiiviiiixiiiiviiii\\n"` | `iiiiviiiixiiiiviiii\n` | `iiiiviiiixiiiiviiii\n` | `iiiiviiiixiiiiviiii\n` |
| `"foo\"bar"` | `foo"bar` | `foo"bar` | `foo"bar` |

In double quoted strings, double quotes and backslashes need escaping with a backslash, and in single quoted strings, single quote and backslashes need escaping with a backslash. In v2.5.2, forgetting an escape can lead to odd results due to the regex running out of stack, but this was fixed in 2.6 and 3.3, with 2.6 allowing you to continue after an unescaped backslash, but 3.3 not.

**Comment by robtesch** [comment]
Good stuff, so just to confirm, even for v3.3+, if the input is:
`"p455w0rd123#"`
it will come out as:
`p455w0rd123#`

No need to escape anything since it's in double quotes and does not contain any double quotes or backslashes.

**Comment by GrahamCampbell** [comment]
Yes, that's correct. :)
