### ISSUE TITLE
getenv() no longer working on v3

### ISSUE THREAD

**Issue by ragingdave** [vlucas/phpdotenv#349]
Upon an upgrade to Laravel 5.8, and phpdotenv 3 as a result, getenv is no longer being populated with the values from the .env file. The variables exist in $_ENV and $_SERVER, but are not filled into `getenv()` accesible locations. This is related to https://github.com/beyondcode/nova-tinker-tool/issues/5.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This is not a bug in this package, but an intentional change that has been made in Laravel 5.8's core. Use Laravel's `env` function to read environment variables loaded by the framework.

**Comment by GrahamCampbell** [comment]
For comparison. In 5.7, we have:

https://github.com/laravel/framework/blob/v5.7.28/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php

But in 5.8:

https://github.com/laravel/framework/blob/v5.8.2/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php

Note in particular line 91. Laravel no longer uses putenv and getenv because it interferes with other websites running on the server because the function is not threadsafe. This stops secrets from being accidentality leaked from Laravel apps in production due to this thread safety issue.

**Comment by approached** [comment]
Or the good old way `$_ENV['key']`
It works with new and old version.

**Comment by GrahamCampbell** [comment]
> It works with new and old version.

@approached That wasn't what this issue was saying. It is complaining that `getenv` is no longer populated in Laravel, and is intentional, in the framework. The so called ENV superglobal is actually poorly named, and is not really for environment variables in the way you might think. The SERVER variable actually behaves closer to what one might expect for ENV.
