### ISSUE TITLE
Is it possible to use arbitrary strings without quoting anything other than the quotation character?

### ISSUE THREAD

**Issue by specialtactics** [vlucas/phpdotenv#354]
Hi

In upgrading from v2 to v3 we had the "unexpected escape sequence" error. 

I was familiarising myself with the upgrade guide, and I am wondering afterwards if there is any way at all to throw an arbitrary string into an .env file without having to worry about escaping slashes and whatnot. 

Using the bash mentality, I would have assumed that if using single quotes, that nothing should need to be escaped (except single quotes), but since that's not the case, what is the difference between using single and double quotes? Or there isn't any?

And if a value is not quoted, then the '#' will be treated as a comment.

So putting all this together, would it be fair to say regardless of how you put strings into the .env file, you now always need to worry about escaping the backslash (as well as whatever quotation character you use) ?

**Comment by GrahamCampbell** [comment]
> I was familiarising myself with the upgrade guide, and I am wondering afterwards if there is any way at all to throw an arbitrary string into an .env file without having to worry about escaping slashes and whatnot.

No, and this has always been the case, even in v2. You have two options:

1. If you know your string will not contain whitespace or a hash, and will not start with a double or single quote, then you will be fine to just paste it in, without any quotes. Otherwise, you will need option 2.
2. If you want to enclose your string in double quotes, then any double quote character will need a backslash in front of it, and any literal backslash also needs escaping with a backslash. You need escape anything else. All other characters will be valid, including whitespace and hashes.

**Comment by specialtactics** [comment]
Ok, thanks !

**Comment by GrahamCampbell** [comment]
:)
