### ISSUE TITLE
What is a valid names for env variables in .env file?

### ISSUE THREAD

**Issue by KarelWintersky** [vlucas/phpdotenv#372]
What is a valid names for env variables in .env file?

Is valid `NGINX::CACHE_USE` for key? 

What is an invalid symbols in env keys?

**Comment by GrahamCampbell** [comment]
No. Names must be non-empty, and made up of a-z, A-Z, 0-9, or periods or underscores.

https://github.com/vlucas/phpdotenv/blob/v3.6.0/src/Parser.php#L81-L91

**Comment by GrahamCampbell** [comment]
Does docker allow colons in names in its env file implementation?

**Comment by KarelWintersky** [comment]
> Does docker allow colons in names in its env file implementation?

dont' know. I think, not.

**Comment by GrahamCampbell** [comment]
I'd like to keep us on par with other implementations.

**Comment by whoisninjaturtle** [comment]
@GrahamCampbell Sorry to necro but in lieu of opening a new ticket, I'm currently facing an issue because the regex restricts slashes of both varieties from the variable name and I'm wondering if there's a deeper technical restriction behind that. 
`$_ENV['a\namespaced\thing']` is a valid array key to PHP and there is at least one framework that support this; see CodeIgniter's implementation where something like `Config\SimpleConfig.name = George` is perfectly valid.
Cheers
