### ISSUE TITLE
README needs updating!

### ISSUE THREAD

**Issue by KarelWintersky** [vlucas/phpdotenv#400]
I use {"vlucas/phpdotenv": "^4.0.1"}

Now:
```
public static function Dotenv::create(Repository\RepositoryInterface $repository, $paths, $file = null) Dotenv
```
not compatible with old call:
```
Dotenv::create(__DIR__, '_env')
```

```
Dotenv::createImmutable( dirname(__DIR__, 1) . '/configs/' ,
        [
            'global', 'credentials', 'options'
        ])->load();
```
reports:
```
Unable to read any of the environment file(s) at [/var/www/project/configs/Array]
```

I'm forced now to revert depencecy to phpdotenv 3.3 and can't use new functionality. 

Please, don't break compatibility!

**Comment by GrahamCampbell** [comment]
Please read the upgrading guide.

**Comment by GrahamCampbell** [comment]
> V4 has again changed the way you initialize the `Dotenv` class. If you want immutable loading of environment variables, then replace `Dotenv::create` with `Dotenv::createImmutable`, and if you want mutable loading, replace `Dotenv::create` with `Dotenv::createMutable` and `->overload()` with `->load()`. The `overload` method has been removed in faviour of specifying mutability at object construction.

**Comment by GrahamCampbell** [comment]
V3 code:

```php
Dotenv::create(__DIR__, '_env')->load();
```

V4 code:

```php
Dotenv::createImmutable(__DIR__, '_env')->load();
```

**Comment by GrahamCampbell** [comment]
> Please, don't break compatibility!

Everything that was possible in v3 is still possible in v4, and more? I don't understand what you say has broken, other than the fact that there is an upgrading path from v3 to v4?

**Comment by GrahamCampbell** [comment]
> Dotenv::createImmutable( dirname(__DIR__, 1) . '/configs/' ,
>         [
>             'global', 'credentials', 'options'
>         ])->load();

This code won't work in v4.0.1. That needs 4.1-dev, which will become 4.1.0 soon.

**Comment by GrahamCampbell** [comment]
As I said before, if you need support for multiple directories, you need, for the moment:

```json
    "require": {
        "vlucas/phpdotenv": "^4.1@dev"
    },
```

**Comment by KarelWintersky** [comment]
A lot of code for solve simple problem :( 
More and more code. More and more abstraction layers.

**Comment by GrahamCampbell** [comment]
It's actually simpler than before, and more flexible. In particular, the `Dotenv` class has a simpler interface than ever before, dispute there being more things to customise. Just having lots of methods on that class with large lists of parameters would be so hard to use.

**Comment by GrahamCampbell** [comment]
The new builder classes may initially appear overkill, but I've really focused on usability. There are no big param lists that are confusing and hard to remember the order. Users just say what they want to do, then at the end, they get the class they want, configured in the way they want it.

**Comment by GrahamCampbell** [comment]
I really hated the old design with `overload` and `load`. I much prefer the repository tracking that, from the start.

**Comment by KarelWintersky** [comment]
I use only load, without overload (and don't have any ideas about usablity of 'overload')

sorry for poor english ;)

**Comment by GrahamCampbell** [comment]
Don't worry, overload was a bad name for it too, which is also a reason for the design change, other than the internal code structure that I didn't like. Nobody knew the difference between `load` and `overload`, native English speaking, or not. The new design makes people choose if they want to "load" or "overload" ahead of time, by telling the repository if it's mutable or immutable.

**Comment by KarelWintersky** [comment]
My case is:
- load configuration for site from one or more `env` files 
- have nested values like `PATH.LOGS = ${PATH.INSTALL}/logs/`
- have access to values via `getenv('PATH.LOGS')`
- have access to configuration via static call like `Config::get('path.logs')` or `_c('path.logs')` (helper method)

**Comment by GrahamCampbell** [comment]
> More and more abstraction layers.

We know have `Dotenv`, which takes 3 objects into its constructor, all with very simple interfaces, with clearly defined jobs.

1. The "store" reads and returns the merged content of any env files. This used to just be exactly one env file in v1, but since then, there have been more and more complex requirements for where to look for files, so it made sense to abstact this away, so `Dotenv` just says, give me a "store", and I'll call `read()` on it.
2. The "repository" is how `Dotenv` interfaces with the "environment". In v1, simply using `getenv` and `putenv` was not good enough, since these functions are not threadsafe, so users wanted a way to customise what was used. But, then, the customisation requirements are complex, which lead to people forking and editing, or extending classes. I want to encourage composition of code, rather than forking the code or extending its classes.
3. The "loader" now just is given a repository and the raw content, and told to parse the content, using the repository to interface with the environment. Not only does it set variables on that, but it also reads them too, in order to implement variable interpolation.

**Comment by GrahamCampbell** [comment]
> My case is

Everyone's use case is different, and this is why the codebase has evolved in the way that it has, to support complex use cases, while maintaining a simple `Dotenv` class.

In order to make sure I've got the changes right between 4.0.1 and 4.1.0, there has not been a release yet. I want to make sure everything is as simple and clear as possible. Simple doesn't mean one class with a mess of code in.

**Comment by GrahamCampbell** [comment]
> there has not been a release yet.

This is because once I tag 4.1.0, the API becomes final, and cannot be broken until v5, and I don't want another breaking release for another year or so, if there is another one in the future.

**Comment by GrahamCampbell** [comment]
> README needs updating!

Wait, so which part of the README has an error?

**Comment by GrahamCampbell** [comment]
`v4.1.0` has been tagged now.

**Comment by KarelWintersky** [comment]
> The "repository" is how Dotenv interfaces with the "environment".

Is it possible to use DotEnv with 
https://packagist.org/packages/m1/vars
or
https://packagist.org/packages/hassankhan/config

as repository? How?

**Comment by GrahamCampbell** [comment]
If you wrote a repository/adapter that interfaced with them, yes. Nothing is shipped with the package core though.
