### ISSUE TITLE
Multiply loading files does not work at v4.1.0

### ISSUE THREAD

**Issue by KarelWintersky** [vlucas/phpdotenv#401]
At composer.json : `"vlucas/phpdotenv": "^4.1.0",`

```
Dotenv::createImmutable( '/var/www/config/', [ '_env', '_env.options' ])->load();
```
My `_env` file: 
```
IS_PRODUCTION   = 0
```
My `_env.options` file: 
```
VERSION         = "ruby"
```

Now, I casts:

`var_dump(getenv('IS_PRODUCTION'));`

Result is `0` (expected)

But `var_dump(getenv('VERSION'))` returns `false` (environment variable not loaded or not mapped)

**Comment by KarelWintersky** [comment]
I think, 'createImmutable' creates immutable instance of environment for `_env` file. And `_env.options` can't change it. :(

**Comment by GrahamCampbell** [comment]
You need to call:

```
Dotenv::createImmutable( '/var/www/config/', [ '_env', '_env.options' ], false)->load();
```

By default, we only read the first file to avoid breaking backwards compatibility in 4.x. You must pass that third parameter to disable "short circuit mode".

**Comment by GrahamCampbell** [comment]
> I think, 'createImmutable' creates immutable instance of environment for _env file. 

No, the immutable part just means that if VERSION was already defined before we try to load the file, then we don't redefine it. This is the beahviour that has been the default since 1.0.0. If you want it to always set the variables, use the muttble version of the method.

Though, neither make a difference when it comes to loading more than one file. As I said above, and in the original issue when you asked, you need to pass the third parameter to disable short circuit mode.

**Comment by KarelWintersky** [comment]
Will work definition:
```
Dotenv::createImmutable( '/var/www/config/', [ '_env*' ], false)->load();
```
?

**Comment by GrahamCampbell** [comment]
No.

**Comment by GrahamCampbell** [comment]
If you want something like that, you'd have to implement your own `Store`.
