### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by esjdev** [vlucas/phpdotenv#462]
What is the difference between using phpdotenv and the code below?

````````php
function _env($name)  {
    $envPath = realpath(dirname(__FILE__) . '/.env');
    $env = parse_ini_file($envPath);

    return $env[$name];
}

echo _env('APP_URL');
````````

**Comment by GrahamCampbell** [comment]
That code will be very slow since it is loading the file over and over. Also, ini files are not the same as env files, so you won't be able to use the same syntax. Moreover, other 3rd party code looking for env variables in `$_SERVER` won't work. For example, the AWS SDK looking for credentials, or the Bugsnag notifier.

**Comment by esjdev** [comment]
> That code will be very slow since it is loading the file over and over. Also, ini files are not the same as env files, so you won't be able to use the same syntax. Moreover, other 3rd party code looking for env variables in `$_SERVER` won't work. For example, the AWS SDK looking for credentials, or the Bugsnag notifier.

Thank you very much for taking this question :D
