### ISSUE TITLE
Feature proposal: isConstant

### ISSUE THREAD

**Issue by tomkyle** [vlucas/phpdotenv#471]
Like the lib provides `$dotenv->required('FOO')->isInteger()` and `->isBoolean()`, a new **`->isConstant()`** would be useful. Consider this example, where I'd expect `getenv('LOGLEVEL')` to return a valid constant name. This would allow to not hardcode-reflect constant values.

```ini
# .dotenv
LOGLEVEL=\Psr\Log\LogLevel::INFO
```
But what if the constant itself has changed, or has disappeared from source code? It needs some steps, however, to grab the constant value, because built-in function [constant](https://www.php.net/manual/en/function.constant.php) will return `null` on undefined constants:
```php
<?php
$dotenv->required('LOGLEVEL')->notEmpty();
$loglevel = getenv('LOGLEVEL');
$loglevel = !is_null($loglevel) ? constant($loglevel) : \Psr\Log\LogLevel::INFO;

⚠️ // $loglevel may still be null when no such constant exists.
```
A new **`->isConstant()`** check could internally use the `constant()` part and throw `RuntimeException` if its return value is `null`:

```php
try {
  $dotenv->required('LOGLEVEL')->isConstant();
  $loglevel = constant(getenv('LOGLEVEL'));
} 
catch (\RuntimeException $e) {
  $e->getMessage();
  // One or more environment variables failed assertions: LOGLEVEL is not a constant.
}
```

What do you think? If this makes sense for you, I can tinker with the `Validator.php` and send PR.
Regards, 
Carsten.

**Comment by GrahamCampbell** [comment]
I am not sure how I feel about your .env file having prior knowledge of the string value of constants, which could change. Instead, I would recommend you reading the env variable into a switch statement, and returning the constant you want like that.

For this reason, the use case of isConstant is not justified, since ist encourages non-SOLID code.

---

NB You should avoid using the `getenv` function because it is not threadsafe. Instead, use `$_SERVER` (yes, PHP did a terrible job of naming this stuff).

NB2 If you still really want this, you can extend the validator and dotenv class. Both of these classes are not final. ;)

**Comment by GrahamCampbell** [comment]
Oh, I see. You wanted the value to be the name of the constant, and not the value.

**Comment by GrahamCampbell** [comment]
Possibly I could just make the `assert` function public. Then you could do `->assert('defined', 'is not a constant')`.

**Comment by tomkyle** [comment]
@GrahamCampbell, thank you for your thoughts, and also your hint with the `defined` function. – Admittedly, something like _check-if-sth-refers-to-a-constant_ might be quite seldom. So, if you made `assert` public this would add enough flexibility to serve such requirements. Thank you!

**Comment by GrahamCampbell** [comment]
`Validator::assert` and `Validator::assertNullable` will be public in `v5.3.0` when it is released later today. :)
