### ISSUE TITLE
.env parameters skipped when system is busy

### ISSUE THREAD

**Issue by BasvanH** [vlucas/phpdotenv#483]
Hello,

We've noticed when the system is executing a lot of MYSQL calls we occasionally get errors that the default settings for the ENV parameters is used.

`[2021-04-01 00:01:59] local.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: insert into ...)`

```
'host' => env('DB_HOST', '127.0.0.1'),
'port' => env('DB_PORT', '3306'),
'database' => env('DB_DATABASE', 'forge'),
'username' => env('DB_USERNAME', 'forge'),
'password' => env('DB_PASSWORD', ''),
```

Using:
- PHP 7.4.12 
- Laravel Framework 7.25.0
- phpdotenv 4.1-dev

What could be the cause of this?

Kind regards,
Bastiaan

**Comment by GrahamCampbell** [comment]
This is a known limitation because PHP's getenv and putenv are not threadsafe. You should cache your config `artisan config:cache` or turn off using getenv and putenv to avoid this issue (in your app bootstrap file before loading the app, include `Illuminate\Support\Env::disablePutenv()` - note that this will break any and all `getenv` calls - `$_SERVER` should be used by all package code, but people always get this wrong because of the way things are named).
