### ISSUE TITLE
Undefined index: USERNAME

### ISSUE THREAD

**Issue by robineero** [vlucas/phpdotenv#523]
I am having issues with .env index names. `USER` and `USERNAME` can not be used as index names? For some reason only these variables are not loaded from the .env and are therefore undefined.

```
$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();
$username = $_ENV['USERNAME'];
```
This results in `PHP Notice:  Undefined index: USERNAME` but works well with `USER_NAME` and everything else.

**Comment by benjaminhaeberli** [comment]
Hi @robineero ! It's probably the same issue as the #137 : `USER` and `USERNAME` are probably already defined by another process. Try to write `echo getenv('USERNAME')` before those 3 lines and look at the result.

To solve this, you have two choices :
- Use a non-used variable name such as `USER_NAME` or a prefix like `MYAPP_USERNAME`
- Use ``Dotenv::createMutable(__DIR__)`` instead of ``Dotvenv::createImmutable(__DIR__)`` - See https://github.com/vlucas/phpdotenv#immutability-and-repository-customization

Cheers ✌️
